describe ('App teste',()=>{

    it('Caso de teste: Adicionando Equipe',()=>{
    cy.visit('http://localhost:3001')
    cy.get('#email').type('juri@gmail.com')
    cy.get('#password').type('Fetin@2024')
    cy.get('.ant-btn-primary').click()  
    cy.get('[style="margin: 15px;"]').click()
    cy.get('#teamNumber').type('10')
    cy.get('#projectName').type('Smart House')
    cy.get('#member1Name').type('Ana Luiza')
    cy.get('#member1Email').type('ana.taveira@gmail.com')
    cy.get(':nth-child(5) > .ant-row > .ant-col > .ant-form-item-control-input > .ant-form-item-control-input-content > #member2Name').type('Mateus Rodrigues')
    cy.get('#member2Email').type('mateus@gmail.com')
    cy.get(':nth-child(7) > .ant-row > .ant-col > .ant-form-item-control-input > .ant-form-item-control-input-content > #member2Name').type('Joao Henrique')    
    cy.get('#member3Email').type('joao@gmail.com')
    cy.get('#member4Name').type('Jessica Jones')
    cy.get('#member4Email').type('jessica@gmail.com')    
    cy.get('#advisorName').type('Jurandir')
    cy.get('#advisorEmail').type("juri@gmail.com")
    cy.get('.ant-form-item-control-input-content > .ant-btn').click()    
    })    


    it('Caso de teste: Adicionar Equipe sem informações',()=>{
    cy.visit('http://localhost:3001')
    cy.get('#email').type('juri@gmail.com')
    cy.get('#password').type('Fetin@2024')
    cy.get('.ant-btn-primary').click()
    cy.get('[style="margin: 15px;"]').click()
    cy.get('.ant-form-item-control-input-content > .ant-btn').click()
    cy.get('#teamNumber_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o número da equipe (até 3 caracteres)')
    cy.get('#projectName_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o nome do projeto (até 65 caracteres)')
    cy.get('#member1Name_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o nome do integrante 01 (até 50 caracteres)')
    cy.get('#member1Email_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o email do integrante 01 (até 30 caracteres)')
    cy.get(':nth-child(5) > .ant-row > .ant-col > [style="display: flex; flex-wrap: nowrap;"] > #member2Name_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o nome do integrante 01 (até 50 caracteres)')
    cy.get('#member2Email_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o email do integrante 01 (até 30 caracteres)')
    cy.get(':nth-child(7) > .ant-row > .ant-col > [style="display: flex; flex-wrap: nowrap;"] > #member2Name_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o nome do integrante 01 (até 50 caracteres)')
    cy.get('#member3Email_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o email do integrante 03 (até 30 caracteres)')
    cy.get('#member4Name_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o nome do integrante 02 (até 50 caracteres)')
    cy.get('#member4Email_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o email do integrante 03 (até 30 caracteres)')
    cy.get('#advisorName_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o nome do projeto (até 65 caracteres)')
    cy.get('#advisorEmail_help > .ant-form-item-explain-error').should('contain.text','Por favor, insira o nome do projeto (até 65 caracteres)')

})

})